# Generated by Django 5.2.7 on 2025-10-30 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_proje_cached_imza_arsa_payi'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Görev Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Detaylı Açıklama')),
                ('son_tarih', models.DateField(blank=True, null=True, verbose_name='Son Teslim Tarihi')),
                ('durum', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('YAPILDI', 'Yapıldı'), ('ERTELENDI', 'Ertelendi'), ('IPTAL_EDILDI', 'İptal Edildi')], default='BEKLEMEDE', max_length=50, verbose_name='Durum')),
                ('atanan_kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atanan_gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Personel')),
                ('malik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.malik', verbose_name='İlgili Malik (Opsiyonel)')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proje', verbose_name='İlgili Proje')),
            ],
            options={
                'verbose_name': 'Görev (Task)',
                'verbose_name_plural': 'Görev Yönetimi',
                'ordering': ['son_tarih'],
            },
        ),
    ]
