# Generated by Django 5.2.7 on 2025-10-31 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gorev'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gorev',
            options={'ordering': ['durum', 'son_teslim_tarihi'], 'verbose_name': 'Personel Görevi', 'verbose_name_plural': 'Personel Görevleri'},
        ),
        migrations.AlterModelOptions(
            name='kullanici',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Kullanıcı (Personel)', 'verbose_name_plural': 'Kullanıcılar (Personeller)'},
        ),
        migrations.RenameField(
            model_name='gorev',
            old_name='malik',
            new_name='ilgili_malik',
        ),
        migrations.RenameField(
            model_name='gorev',
            old_name='son_tarih',
            new_name='son_teslim_tarihi',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='telefon_numarasi',
            new_name='telefon',
        ),
        migrations.RemoveField(
            model_name='gorev',
            name='atanan_kullanici',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='unvan',
        ),
        migrations.AddField(
            model_name='gorev',
            name='atanan_personel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Personel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gorev',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gorev',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gorev',
            name='oncelik',
            field=models.CharField(choices=[('ACIL', 'Acil'), ('YUKSEK', 'Yüksek'), ('ORTA', 'Orta'), ('DUSUK', 'Düşük')], default='ORTA', max_length=20, verbose_name='Öncelik Seviyesi'),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='ise_baslangic_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='İşe Başlangıç Tarihi'),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='profil_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to='kullanici_profilleri/', verbose_name='Profil Fotoğrafı'),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='uzmanlik_alani',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uzmanlık Alanı'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='aciklama',
            field=models.TextField(default=1, verbose_name='Görev Açıklaması'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gorev',
            name='durum',
            field=models.CharField(choices=[('YENI', 'Yeni'), ('DEVAM_EDIYOR', 'Devam Ediyor'), ('BEKLEMEDE', 'Beklemede'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL_EDILDI', 'İptal Edildi')], default='YENI', max_length=20, verbose_name='Durum'),
        ),
    ]
