# Generated by Django 5.2.7 on 2025-10-31 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_hisse_hisse_orani_remove_proje_proje_konumu_and_more'),
        ('users', '0003_alter_gorev_options_alter_kullanici_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorev',
            name='ilgili_malik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gorevleri', to='projects.malik', verbose_name='İlgili Malik (Opsiyonel)'),
        ),
    ]
