# Generated by Django 5.2.7 on 2025-10-31 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_gorev_ilgili_malik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gorev',
            options={'ordering': ['durum', 'son_teslim_tarihi'], 'verbose_name': 'Personel Görevi (İş Akışı)', 'verbose_name_plural': 'Personel Görevleri (İş Akışları)'},
        ),
        migrations.AddField(
            model_name='gorev',
            name='bagimli_oldugu_gorevler',
            field=models.ManyToManyField(blank=True, related_name='bu_goreve_bagimli_olanlar', to='users.gorev', verbose_name='Bağımlı Olduğu Görevler'),
        ),
        migrations.AddField(
            model_name='gorev',
            name='olusturan_personel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Görevi Oluşturan'),
        ),
        migrations.AddField(
            model_name='gorev',
            name='tahmini_sure_saat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tahmini Süre (Saat)'),
        ),
        migrations.AddField(
            model_name='gorev',
            name='tamamlanma_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi'),
        ),
        migrations.AddField(
            model_name='gorev',
            name='ust_gorev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_gorevler', to='users.gorev', verbose_name='Üst Görev (Ana Görev)'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='atanan_personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atanan_gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Personel'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='durum',
            field=models.CharField(choices=[('YENI', 'Yeni'), ('DEVAM_EDIYOR', 'Devam Ediyor'), ('BEKLEMEDE', 'Beklemede'), ('GOZDEN_GECIRILIYOR', 'Gözden Geçiriliyor'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL_EDILDI', 'İptal Edildi')], default='YENI', max_length=50, verbose_name='Durum'),
        ),
    ]
