"""
Django settings for kpy_sistemi project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# KRİTİK DÜZELTME: 'reverse_lazy' import'u ayar dosyasından kaldırıldı.
# Bu, yükleme sırası sorunlarına (circular import) neden oluyordu.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lam^=ue7tae=zb+lqj!&xe^55+#_8&^203%4&@s_d1z$m)7ru5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Yeni AdminLTE Teması
    'users',    # User Modülü
    'projects', # Project Modülü
    'finance',  # Finans Modülü
    'envanter', # envanter Modülü
    'saha',     # saha Modülü

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kpy_sistemi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # KRİTİK DÜZELTME: Yeni templates klasörümüzü buraya ekliyoruz
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kpy_sistemi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Projenin varsayılan Kullanıcı modelini bizim oluşturduğumuz modelle değiştiriyoruz.
# Format: 'uygulama_adi.ModelAdi'
AUTH_USER_MODEL = 'users.Kullanici'



STATIC_URL = 'static/'

# Adım 18'de 'collectstatic' komutunun dosyaları toplayacağı ana klasör
# Proje ana dizininde (manage.py'nin yanında) 'staticfiles' adında bir klasör oluşturacak
STATIC_ROOT = BASE_DIR / 'staticfiles'


# -----------------------------------------------------------------
# MEDYA (DOSYA YÜKLEME) AYARLARI (FAZ 3 - EVRAK MODELİ İÇİN)
# -----------------------------------------------------------------

# Yüklenen dosyaların web üzerindeki URL'si (örn: /media/evraklar/...)
MEDIA_URL = '/media/'

# Yüklenen dosyaların sunucuda fiziksel olarak saklanacağı klasör
# Proje ana dizininde (manage.py'nin yanında) 'mediafiles' adında bir klasör oluşturacak
MEDIA_ROOT = BASE_DIR / 'mediafiles'


# -----------------------------------------------------------------
# CELERY / REDIS AYARLARI (FAZ 5 - OTOMASYON İÇİN)
# -----------------------------------------------------------------
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' # Redis'i mesaj kuyruğu (broker) olarak kullan
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0' # Sonuçları Redis'te sakla
CELERY_ACCEPT_CONTENT = ['json'] # İçerik tipini JSON yap
CELERY_TASK_SERIALIZER = 'json' # Görevleri JSON ile serileştir
CELERY_RESULT_SERIALIZER = 'json' # Sonuçları JSON ile serileştir
CELERY_TIMEZONE = 'Europe/Istanbul' # Türkiye saat dilimini kullan


# -----------------------------------------------------------------
# CELERY PERİYODİK GÖREVLERİ (FAZ 5)
# -----------------------------------------------------------------
CELERY_BEAT_SCHEDULE = {
    # 1. Proje İstatistiklerini Güncelleme Görevi (Örn: Her saat başı)
    'proje-istatistik-guncelle': {
        'task': 'projects.tasks.toplu_istatistik_guncelle',
        'schedule': 3600.0,  # 3600 saniye = 1 saat
    },
    # 2. Doğum Günü SMS Otomasyonu (Örn: Her gün sabah 9'da)
    'dogum-gunu-sms-gonder': {
        'task': 'projects.tasks.dogum_gunu_sms_gonder',
        'schedule': 86400.0,  # 86400 saniye = 1 gün
    },
}


# -----------------------------------------------------------------
# JAZZMIN/ADMINLTE TEMA VE MENÜ AYARLARI (FAZ 5 - KULLANICI DENEYİMİ)
# -----------------------------------------------------------------

JAZZMIN_UI_TWEAKS = {
    # Temel görsel ayarlar
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark", # Navigasyon çubuğunu koyu (standart) tutalım
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light", # Navigasyon çubuğunu beyaz/açık yaptık
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True, # Sol menü sabit kalsın (daha iyi UX)
    "sidebar": "sidebar-light-primary", # Sol menü açık/beyaz yaptık
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": True, 
    "sidebar_nav_flat_style": True,
    "theme": "yeti", # Yeti (Açık ve okunaklı bir tema)
    "dark_mode_listener": False,
    "theme_switch_in_navbar": False,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


# kpy_sistemi/settings.py dosyasındaki JAZZMIN_SETTINGS bölümü
# (Yaklaşık 208. satırdan itibaren)

JAZZMIN_SETTINGS = {
    # ... (Diğer ayarlar aynı kalır)

    # Custom icons for the side menu apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.group": "fas fa-users",
        "users.Kullanici": "fas fa-user-tie",
        "users.Gorev": "fas fa-tasks",
        "projects.Proje": "fas fa-city",
        "projects.Malik": "fas fa-handshake",
        "projects.Hisse": "fas fa-file-signature",
        "projects.BagimsizBolum": "fas fa-building",
        "projects.Evrak": "fas fa-file-alt",
        "projects.GorusmeKaydi": "fas fa-comments",
        "projects.ProjeYetkisi": "fas fa-user-shield",
        "finance.MaliyetKalemi": "fas fa-tags",
        "finance.Maliyet": "fas fa-dollar-sign",
        "envanter.Demirbas": "fas fa-laptop",
        "envanter.Zimmet": "fas fa-exchange-alt",
        
        # YENİ EKLENEN/VARSAYILAN MODÜL İKONLARI (Saha Modülü için planlanan modeller)
        "saha.GunlukRapor": "fas fa-clipboard-list",
        "saha.TahliyeTakibi": "fas fa-house-damage",
        
    },

    # Ana Menü Yapısı (Modelleri uygulamalara göre sıralar)
    "order_with_respect_to": [
        "projects", "finance", "saha", "envanter", "users", "auth", # 'saha' eklendi
    ],

    # Sol Menü (Side Menu) Yapısı (Eksik menüler eklendi, sıralama güncellendi)
    "menu": [
        # 1. Ana Panel (Dashboard)
        {"name": "Ana Panel", "url": "admin:index", "icon": "fas fa-home"},
        
        # 2. PROJELER (Yönetim Modülü)
        {"app": "projects", "name": "PROJELER & TEMELLER", "icon": "fas fa-city", "models": [
            "projects.Proje",
            "projects.ProjeYetkisi",
        ]},

        # 3. HUKUK & MALİK YÖNETİMİ (CRM)
        {"app": "projects", "name": "HUKUK & MALİK YÖNETİMİ (CRM)", "icon": "fas fa-handshake", "models": [
            "projects.Malik",
            "projects.BagimsizBolum",
            "projects.Hisse",
            "projects.GorusmeKaydi",
        ]},

        # 4. SAHA & İŞ YÖNETİMİ
        {"app": "saha", "name": "SAHA & İŞ YÖNETİMİ", "icon": "fas fa-hard-hat", "models": [
            # KRİTİK DÜZELTME: Bu bir model değil, bir rapor/dashboard. 
            # Bu menü öğesini models listesinden çıkarıp custom link ekleyelim.

            # Bu kısmı (modelleri listelemek yerine) URL'ye yönlendirelim:
            {"name": "Saha Yönetim Paneli", "url": "saha:saha_dashboard", "icon": "fas fa-tachometer-alt"},
            "saha.TahliyeTakibi",   # Tahliye Takibine doğrudan link
            "saha.GunlukSahaRaporu", # Günlük Raporlara doğrudan link
            # Eksik modelleri de ekleyelim (Eski admin.py'de vardı)
            {"model": "saha.Taseron", "label": "Taşeron Yönetimi"},
            {"model": "saha.IsTakvimiGorevi", "label": "İş Takvimi ve Görevler"},
        ]},
        
        # 5. DİJİTAL ARŞİV (DMS)
        {"app": "projects", "name": "DİJİTAL ARŞİV (DMS)", "icon": "fas fa-file-archive", "models": [
            "projects.Evrak",
        ]},

        # 6. BÜTÇE & MALİYET
        {"app": "finance", "name": "BÜTÇE & MALİYET", "icon": "fas fa-money-bill-wave", "models": [
            "finance.Maliyet",
            {"model": "finance.MaliyetKalemi", "label": "Maliyet Kalemleri (Tanım)"},
        ]},
        
        # 7. İK & ENVANTER YÖNETİMİ
        {"app": "envanter", "name": "İK & ENVANTER YÖNETİMİ", "icon": "fas fa-box", "models": [
            "envanter.Demirbas",
            "envanter.Zimmet",
        ]},
        
        # 8. İLETİŞİM & BİLDİRİMLER (*** EKSİK MENÜ EKLENDİ - README Madde 7 ***)
        {
            "name": "İLETİŞİM & BİLDİRİMLER",
            "icon": "fas fa-bell",
            "items": [
                {
                   'name': 'Toplu SMS/E-Posta Gönderimi',
                   'url': 'users:toplu_bildirim', # Custom view gerektirir
                   'icon': 'fas fa-paper-plane',
                   'permissions': ['auth.view_user'],
                },
                {
                   'name': 'Otomasyon Yönetimi (Celery)',
                   'url': 'admin:dogum_gunu_otomasyon', # Custom view gerektirir
                   'icon': 'fas fa-robot',
                   'permissions': ['auth.view_group'], 
                },
            ]
        },
        
        # 9. ANALİZ & RAPORLAR (Menü sırası mantıksal olarak sona alındı)
        {
            "name": "ANALİZ & RAPORLAR", 
            "icon": "fas fa-chart-pie", 
            "items": [
                {
                    "name": "Malik Direnç Analizi", 
                    "url": "projects:direnc_analizi_raporu", 
                    "icon": "fas fa-chart-bar",
                    "permissions": ["auth.view_group"]
                },

                {
                   'name': 'Bütçe vs. Fiili Raporu',
                   # URL adı düzeltildi.
                   'url': 'finance:butce_vs_fiili_raporu', 
                   'icon': 'fas fa-money-check-alt',
                   'permissions': ['auth.view_user'], 
                },
                
                # README'deki "Proje İlerleme Hunisi (Funnel)" raporu eklendi
                {
                    'name': 'Proje İlerleme Hunisi',
                    'url': 'projects:ilerleme_hunisi_raporu', # Custom view gerektirir
                    'icon': 'fas fa-stream',
                    'permissions': ['auth.view_user'], 
                },
            ]
        },

        # 10. SİSTEM YÖNETİMİ & YETKİLER
        {"app": "users", "name": "KULLANICI & YETKİ YÖNETİMİ", "icon": "fas fa-users-cog", "models": [
            "users.Kullanici",
            "users.Gorev",
            {"model": "auth.group", "label": "Rol Grupları (Gelişmiş)"},
        ]},
    ]
}