# Generated by Django 5.2.7 on 2025-10-29 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_adi', models.CharField(max_length=255, verbose_name='Proje Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Proje Açıklaması')),
                ('proje_konumu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proje Konumu (İl/İlçe)')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Proje Aktif mi?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='ProjeYetkisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PROJE_MUDURU', 'Proje Müdürü'), ('SAHA_TEMSILCISI', 'Saha Temsilcisi'), ('HUKUKCU', 'Hukukçu'), ('FINANS', 'Finans'), ('MISAFIR', 'Misafir (Sadece Görüntüleme)')], default='MISAFIR', max_length=50, verbose_name='Projedeki Rolü')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proje', verbose_name='Yetkili Proje')),
            ],
            options={
                'verbose_name': 'Proje Yetkisi',
                'verbose_name_plural': 'Proje Yetkileri',
                'unique_together': {('kullanici', 'proje')},
            },
        ),
    ]
