# Generated by Django 5.2.7 on 2025-10-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagimsizBolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ada')),
                ('parsel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parsel')),
                ('pafta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pafta')),
                ('nitelik', models.CharField(max_length=100, verbose_name='Niteliği (Daire, Dükkan, Arsa...)')),
                ('tapu_alani_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tapu Alanı (m²)')),
                ('arsa_payi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Arsa Payı (Örn: 120)')),
                ('arsa_paydasi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Arsa Paydası (Örn: 24000)')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.proje', verbose_name='İlgili Proje')),
            ],
            options={
                'verbose_name': 'Bağımsız Bölüm (Mülk)',
                'verbose_name_plural': 'Bağımsız Bölümler (Mülkler)',
            },
        ),
        migrations.CreateModel(
            name='Malik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('tc_kimlik_no', models.CharField(blank=True, max_length=11, null=True, verbose_name='TC Kimlik No')),
                ('telefon_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 1')),
                ('telefon_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta Adresi')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.proje', verbose_name='İlgili Proje')),
            ],
            options={
                'verbose_name': 'Malik (Mülk Sahibi)',
                'verbose_name_plural': 'Malikler (Mülk Sahipleri)',
                'unique_together': {('proje', 'tc_kimlik_no')},
            },
        ),
        migrations.CreateModel(
            name='Hisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hisse_orani', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Hisse Oranı (Örn: 0.50 = %50)')),
                ('durum', models.CharField(choices=[('IMZALADI', 'İmzaladı'), ('BEKLEMEDE', 'Beklemede'), ('REDDETTI', 'Reddetti'), ('HUKUKI_SURECTE', 'Hukuki Süreçte')], default='BEKLEMEDE', max_length=50, verbose_name='İmza Durumu')),
                ('bagimsiz_bolum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.bagimsizbolum', verbose_name='İlgili Bağımsız Bölüm')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.proje', verbose_name='İlgili Proje')),
                ('malik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.malik', verbose_name='Hissedar Malik')),
            ],
            options={
                'verbose_name': 'Hisse (Mülkiyet Kaydı)',
                'verbose_name_plural': 'Hisseler (Mülkiyet Kayıtları)',
            },
        ),
    ]
