# Generated by Django 5.2.7 on 2025-10-29 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_bagimsizbolum_malik_hisse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evrak_adi', models.CharField(max_length=255, verbose_name='Evrak Adı / Başlığı')),
                ('evrak_tipi', models.CharField(choices=[('SOZLESME', 'Sözleşme'), ('TAPU', 'Tapu'), ('VEKALETNAME', 'Vekaletname'), ('RUHSAT', 'Ruhsat (İnşaat/İskan)'), ('PROJE_DOSYASI', 'Proje Dosyası (Mimari vb.)'), ('SAHA_FOTOGRAFI', 'Saha Fotoğrafı'), ('DIGER', 'Diğer Resmi Evrak')], default='DIGER', max_length=50, verbose_name='Evrak Tipi')),
                ('dosya', models.FileField(upload_to='evraklar/%Y/%m/%d/', verbose_name='Dosya')),
                ('aktif_surum_mu', models.BooleanField(default=True, verbose_name='Bu Aktif Sürüm mü?')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='OCR ile Okunan Metin İçerik')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('bagimsiz_bolum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.bagimsizbolum', verbose_name='İlgili Bağımsız Bölüm (Opsiyonel)')),
                ('hisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.hisse', verbose_name='İlgili Hisse (Opsiyonel)')),
                ('malik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.malik', verbose_name='İlgili Malik (Opsiyonel)')),
                ('onceki_surum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.evrak', verbose_name='Önceki Sürüm')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.proje', verbose_name='İlgili Proje')),
            ],
            options={
                'verbose_name': 'Evrak (Dijital Arşiv)',
                'verbose_name_plural': 'Evraklar (Dijital Arşiv)',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='GorusmeKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorusme_tarihi', models.DateTimeField(verbose_name='Görüşme Tarihi ve Saati')),
                ('gorusme_ozeti', models.TextField(verbose_name='Görüşme Özeti / Notlar')),
                ('gorusme_sonucu', models.CharField(blank=True, choices=[('OLUMLU', 'Olumlu'), ('OLUMSUZ', 'Olumsuz'), ('KARARSIZ', 'Kararsız'), ('TEKRAR_GORUSULECEK', 'Tekrar Görüşülecek'), ('ULASILAMADI', 'Ulaşılamadı')], max_length=50, null=True, verbose_name='Görüşme Sonucu')),
                ('gorusmeyi_yapan_personel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Görüşmeyi Yapan Personel')),
                ('malik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.malik', verbose_name='Görüşülen Malik')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proje', verbose_name='İlgili Proje')),
            ],
            options={
                'verbose_name': 'Görüşme Kaydı',
                'verbose_name_plural': 'Görüşme Kayıtları',
                'ordering': ['-gorusme_tarihi'],
            },
        ),
    ]
