# Generated by Django 5.2.7 on 2025-10-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_evrak_gorusmekaydi'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='cached_imza_arsa_payi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Önbellek: İmza Arsa Payı (%)'),
        ),
        migrations.AddField(
            model_name='proje',
            name='cached_toplam_malik_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Önbellek: Toplam Malik Sayısı'),
        ),
    ]
