# Generated by Django 5.2.7 on 2025-10-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_proje_cached_imza_arsa_payi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='cached_imza_arsa_payi',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Önbellek: İmza Arsa Payı (%)'),
        ),
    ]
