# Generated by Django 5.2.7 on 2025-10-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_proje_cached_imza_arsa_payi'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorusmekaydi',
            name='direnc_nedeni',
            field=models.CharField(choices=[('YOK', 'Anlaşma Yok/Gerekli Değil'), ('FIYAT', 'Fiyat Teklifi Yetersiz'), ('VERASET', 'Veraset/Miras Sorunu'), ('PLAN', 'Yeni Proje Planını Beğenmeme'), ('KIRACI', 'Kiracı Sorunu/Tahliye'), ('DIGER', 'Diğer/Özel Durum')], default='YOK', max_length=50, verbose_name='Malik Direnç Nedeni'),
        ),
    ]
