# Generated by Django 5.2.7 on 2025-10-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_gorusmekaydi_direnc_nedeni'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='arsa_paydasi_ortak',
            field=models.PositiveIntegerField(blank=True, help_text='2/3 hesaplaması için projedeki tüm mülklerin ortak paydası.', null=True, verbose_name='Proje Ortak Arsa Paydası (Örn: 24000)'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='cached_imza_arsa_payi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Önbellek: İmza Arsa Payı (%)'),
        ),
    ]
