# Generated by Django 5.2.7 on 2025-10-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_proje_arsa_paydasi_ortak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='toplam_butce',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Proje için ayrılan toplam bütçe tutarı (TL)', max_digits=12, verbose_name='Planlanan Toplam Bütçe'),
        ),
    ]
