# Generated by Django 5.2.7 on 2025-10-31 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_proje_toplam_butce'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisse',
            name='hisse_orani',
        ),
        migrations.RemoveField(
            model_name='proje',
            name='proje_konumu',
        ),
        migrations.AddField(
            model_name='bagimsizbolum',
            name='bolum_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bağımsız Bölüm Numarası'),
        ),
        migrations.AddField(
            model_name='evrak',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Ek Açıklama'),
        ),
        migrations.AddField(
            model_name='hisse',
            name='hisse_orani_pay',
            field=models.PositiveIntegerField(default=1, verbose_name='Hisse Payı'),
        ),
        migrations.AddField(
            model_name='hisse',
            name='hisse_orani_payda',
            field=models.PositiveIntegerField(default=1, verbose_name='Hisse Paydası'),
        ),
        migrations.AddField(
            model_name='hisse',
            name='imza_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='İmza/Red Tarihi'),
        ),
        migrations.AddField(
            model_name='malik',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın'), ('B', 'Belirtilmemiş')], default='B', max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='proje',
            name='ada_parsel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ada/Parsel Bilgisi'),
        ),
        migrations.AddField(
            model_name='proje',
            name='adres',
            field=models.TextField(blank=True, null=True, verbose_name='Proje Adresi'),
        ),
        migrations.AddField(
            model_name='proje',
            name='il',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='proje',
            name='ilce',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='proje',
            name='mahalle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahalle'),
        ),
        migrations.AddField(
            model_name='proje',
            name='proje_amaci',
            field=models.TextField(blank=True, null=True, verbose_name='Proje Amacı'),
        ),
        migrations.AlterField(
            model_name='gorusmekaydi',
            name='gorusmeyi_yapan_personel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaptigi_gorusmeler', to=settings.AUTH_USER_MODEL, verbose_name='Görüşmeyi Yapan Personel'),
        ),
        migrations.AlterField(
            model_name='hisse',
            name='malik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hisseleri', to='projects.malik', verbose_name='Hissedar Malik'),
        ),
        migrations.AlterField(
            model_name='malik',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malikler', to='projects.proje', verbose_name='İlgili Proje'),
        ),
    ]
