# Generated by Django 5.2.7 on 2025-10-30 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_evrak_gorusmekaydi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaliyetKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, unique=True, verbose_name='Maliyet Kalemi Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Maliyet Kalemi',
                'verbose_name_plural': 'Maliyet Kalemleri (Tanımlamalar)',
            },
        ),
        migrations.CreateModel(
            name='Maliyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harcama Tutarı (TL)')),
                ('aciklama', models.TextField(verbose_name='Harcama Açıklaması / Fatura No')),
                ('harcama_tarihi', models.DateField(verbose_name='Harcama Tarihi')),
                ('kaydi_yapan_personel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kaydı Yapan Personel')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.proje', verbose_name='Proje')),
                ('maliyet_kalemi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.maliyetkalemi', verbose_name='Maliyet Kalemi')),
            ],
            options={
                'verbose_name': 'Maliyet (Fiili Harcama)',
                'verbose_name_plural': 'Maliyetler (Fiili Harcamalar)',
                'ordering': ['-harcama_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Butce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planlanan_tutar', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Planlanan Tutar (TL)')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proje', verbose_name='Proje')),
                ('maliyet_kalemi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.maliyetkalemi', verbose_name='Maliyet Kalemi')),
            ],
            options={
                'verbose_name': 'Proje Bütçesi',
                'verbose_name_plural': 'Proje Bütçeleri',
                'unique_together': {('proje', 'maliyet_kalemi')},
            },
        ),
    ]
