# Generated by Django 5.2.7 on 2025-10-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('projects', '0009_remove_hisse_hisse_orani_remove_proje_proje_konumu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butce',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='butceler', to='projects.proje', verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='maliyet',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maliyetler', to='projects.proje', verbose_name='Proje'),
        ),
    ]
