# Generated by Django 5.2.7 on 2025-10-31 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_butce_proje_alter_maliyet_proje'),
        ('projects', '0009_remove_hisse_hisse_orani_remove_proje_proje_konumu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TedarikciVeyaMusteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('TEDARIKCI', 'Tedarikçi (Gelen Fatura)'), ('MUSTERI', 'Müşteri (Giden Fatura)'), ('HER_IKISI', 'Her İkisi')], default='TEDARIKCI', max_length=20, verbose_name='Taraf Tipi')),
                ('ad', models.CharField(max_length=255, verbose_name='Kurum/Kişi Adı')),
                ('vergi_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vergi No / TC Kimlik No')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta Adresi')),
            ],
            options={
                'verbose_name': 'Tedarikçi/Müşteri',
                'verbose_name_plural': 'Tedarikçi/Müşteriler',
                'ordering': ['ad'],
            },
        ),
        migrations.AddField(
            model_name='maliyet',
            name='onay_durumu',
            field=models.CharField(choices=[('BEKLEMEDE', 'Onay Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='ONAYLANDI', max_length=20, verbose_name='Harcama Onay Durumu'),
        ),
        migrations.AlterField(
            model_name='maliyet',
            name='aciklama',
            field=models.TextField(verbose_name='Harcama Açıklaması'),
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('GELEN', 'Gelen Fatura (Gider)'), ('GIDEN', 'Giden Fatura (Gelir)')], max_length=10, verbose_name='Fatura Tipi')),
                ('fatura_no', models.CharField(max_length=100, unique=True, verbose_name='Fatura Numarası')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Fatura Tutarı (TL)')),
                ('vade_tarihi', models.DateField(blank=True, null=True, verbose_name='Vade Tarihi')),
                ('odeme_tarihi', models.DateField(blank=True, null=True, verbose_name='Ödeme / Tahsilat Tarihi')),
                ('durum', models.CharField(choices=[('ODENDI', 'Ödendi / Tahsil Edildi'), ('ODENMEDI', 'Ödenmedi / Tahsil Edilmedi'), ('VADESI_GECTI', 'Vadesi Geçti'), ('KISMI', 'Kısmen Ödendi/Tahsil Edildi')], default='ODENMEDI', max_length=20, verbose_name='Durum')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Ek Açıklama')),
                ('evrak_dosya', models.FileField(blank=True, null=True, upload_to='faturalar/%Y/%m/', verbose_name='Fatura Dosyası (PDF/Resim)')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturalar', to='projects.proje', verbose_name='İlgili Proje')),
                ('karsi_taraf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.tedarikciveyamusteri', verbose_name='Tedarikçi / Müşteri')),
            ],
            options={
                'verbose_name': 'Fatura Kaydı',
                'verbose_name_plural': 'Fatura Kayıtları',
                'ordering': ['-vade_tarihi'],
            },
        ),
        migrations.AddField(
            model_name='maliyet',
            name='ilgili_fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maliyetleri', to='finance.fatura', verbose_name='İlgili Fatura (Opsiyonel)'),
        ),
        migrations.CreateModel(
            name='HarcamaTalep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahmini_tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tahmini Tutar (TL)')),
                ('gerekce', models.TextField(verbose_name='Talep Gerekçesi / Açıklama')),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True)),
                ('onay_durumu', models.CharField(choices=[('BEKLEMEDE', 'Onay Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLEMEDE', max_length=20, verbose_name='Onay Durumu')),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Onay/Red Tarihi')),
                ('gerceklesen_maliyet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.maliyet', verbose_name='Gerçekleşen Maliyet Kaydı (Opsiyonel)')),
                ('maliyet_kalemi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.maliyetkalemi', verbose_name='Planlanan Maliyet Kalemi')),
                ('onaylayan_personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onayladigi_talepler', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan Personel (Opsiyonel)')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proje', verbose_name='İlgili Proje')),
                ('talep_eden_personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yaptigi_talepler', to=settings.AUTH_USER_MODEL, verbose_name='Talebi Yapan Personel')),
            ],
            options={
                'verbose_name': 'Harcama Talep Formu',
                'verbose_name_plural': 'Harcama Talep Formları',
                'ordering': ['talep_tarihi'],
            },
        ),
    ]
