# Generated by Django 5.2.7 on 2025-10-30 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demirbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Demirbaş Adı (Örn: Dell Laptop)')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model')),
                ('seri_no', models.CharField(max_length=255, unique=True, verbose_name='Seri Numarası')),
                ('alinma_tarihi', models.DateField(blank=True, null=True, verbose_name='Satın Alınma Tarihi')),
                ('durum', models.CharField(choices=[('KULLANIMDA', 'Kullanımda (Zimmetli)'), ('DEPO', 'Depoda (Kullanıma Hazır)'), ('ARIZALI', 'Arızalı'), ('HURDA', 'Hurda (Kullanım Dışı)')], default='DEPO', max_length=50, verbose_name='Demirbaş Durumu')),
            ],
            options={
                'verbose_name': 'Demirbaş',
                'verbose_name_plural': 'Demirbaş Listesi',
            },
        ),
        migrations.CreateModel(
            name='Zimmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zimmet_tarihi', models.DateField(verbose_name='Zimmet Tarihi')),
                ('iade_tarihi', models.DateField(blank=True, null=True, verbose_name='İade Tarihi (Boşsa halen zimmetlidir)')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Zimmet Notları (Teslimat vb.)')),
                ('demirbas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envanter.demirbas', verbose_name='Zimmetlenen Demirbaş')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Zimmetlenen Personel')),
            ],
            options={
                'verbose_name': 'Zimmet Kaydı',
                'verbose_name_plural': 'Zimmet Kayıtları',
                'ordering': ['-zimmet_tarihi'],
            },
        ),
    ]
