# Generated by Django 5.2.7 on 2025-10-31 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0001_initial'),
        ('projects', '0008_proje_toplam_butce'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvanterKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150, unique=True, verbose_name='Kategori Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Envanter Kategorisi',
                'verbose_name_plural': 'Envanter Kategorileri',
            },
        ),
        migrations.RemoveField(
            model_name='zimmet',
            name='demirbas',
        ),
        migrations.RemoveField(
            model_name='zimmet',
            name='personel',
        ),
        migrations.CreateModel(
            name='Envanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Varlık Adı/Modeli')),
                ('seri_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Seri/Stok Numarası')),
                ('edinme_tarihi', models.DateField(verbose_name='Edinme Tarihi')),
                ('edinme_maliyeti', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Edinme Maliyeti (TL)')),
                ('durum', models.CharField(choices=[('AKTIF', 'Aktif Kullanımda'), ('DEPO', 'Depoda / Yedekte'), ('BAKIM', 'Bakımda / Arızalı'), ('HURDA', 'Hurda / Kullanım Dışı')], default='DEPO', max_length=50, verbose_name='Mevcut Durumu')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proje', verbose_name='İlgili Proje')),
                ('sorumlu_personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorumlu_envanterler', to=settings.AUTH_USER_MODEL, verbose_name='Mevcut Sorumlu Personel')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envanter.envanterkategorisi', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Envanter (Varlık)',
                'verbose_name_plural': 'Envanterler (Varlıklar)',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='KullanimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim_amaci', models.CharField(max_length=255, verbose_name='Kullanım Amacı/Yeri')),
                ('baslangic_tarihi', models.DateTimeField(verbose_name='Kullanım Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Kullanım Bitiş Tarihi (Boş ise hala kullanılıyor)')),
                ('envanter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envanter.envanter', verbose_name='Kullanılan Envanter')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Kullanan Personel')),
            ],
            options={
                'verbose_name': 'Envanter Kullanım Kaydı',
                'verbose_name_plural': 'Envanter Kullanım Kayıtları',
                'ordering': ['-baslangic_tarihi'],
            },
        ),
        migrations.DeleteModel(
            name='Demirbas',
        ),
        migrations.DeleteModel(
            name='Zimmet',
        ),
    ]
