# Generated by Django 5.2.7 on 2025-10-31 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0002_envanterkategorisi_remove_zimmet_demirbas_and_more'),
        ('projects', '0009_remove_hisse_hisse_orani_remove_proje_proje_konumu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='envanter',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envanterler', to='projects.proje', verbose_name='İlgili Proje'),
        ),
        migrations.AlterField(
            model_name='kullanimkaydi',
            name='envanter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanim_kayitlari', to='envanter.envanter', verbose_name='Kullanılan Envanter'),
        ),
        migrations.AlterField(
            model_name='kullanimkaydi',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envanter_kullanimlari', to=settings.AUTH_USER_MODEL, verbose_name='Kullanan Personel'),
        ),
    ]
