# Generated by Django 5.2.7 on 2025-10-31 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0003_alter_envanter_proje_alter_kullanimkaydi_envanter_and_more'),
        ('projects', '0009_remove_hisse_hisse_orani_remove_proje_proje_konumu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepolamaAlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150, unique=True, verbose_name='Depo/Lokasyon Adı')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres/Konum')),
            ],
            options={
                'verbose_name': 'Depolama Alanı',
                'verbose_name_plural': 'Depolama Alanları',
            },
        ),
        migrations.AlterModelOptions(
            name='envanter',
            options={'ordering': ['ad'], 'verbose_name': 'Envanter (Varlık/Demirbaş)', 'verbose_name_plural': 'Envanterler (Varlıklar/Demirbaşlar)'},
        ),
        migrations.AlterModelOptions(
            name='kullanimkaydi',
            options={'ordering': ['-baslangic_tarihi'], 'verbose_name': 'Envanter Kullanım Kaydı (Zimmet)', 'verbose_name_plural': 'Envanter Kullanım Kayıtları (Zimmetler)'},
        ),
        migrations.AddField(
            model_name='envanter',
            name='amortisman_baslangic_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Amortisman Başlangıç Tarihi'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='amortisman_orani',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Envanterin yıllık amortisman yüzdesi.', max_digits=5, verbose_name='Yıllık Amortisman Oranı (%)'),
        ),
        migrations.CreateModel(
            name='BakimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('PLANLI', 'Planlı Bakım'), ('ARIZA', 'Arıza Onarım'), ('KALIBRASYON', 'Kalibrasyon')], max_length=20, verbose_name='Bakım Tipi')),
                ('bakim_tarihi', models.DateField(verbose_name='Bakım/Arıza Tarihi')),
                ('aciklama', models.TextField(verbose_name='Yapılan İşlem/Arıza Açıklaması')),
                ('maliyet', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bakım Maliyeti (TL)')),
                ('sonuc', models.CharField(max_length=255, verbose_name='Bakım Sonucu (Örn: Tamir Edildi, Parça Değişti)')),
                ('bir_sonraki_bakim_tarihi', models.DateField(blank=True, null=True, verbose_name='Planlanan Sonraki Bakım Tarihi')),
                ('envanter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakim_kayitlari', to='envanter.envanter', verbose_name='İlgili Envanter')),
                ('sorumlu_teknisyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Teknisyen/Personel')),
            ],
            options={
                'verbose_name': 'Bakım/Arıza Kaydı',
                'verbose_name_plural': 'Bakım/Arıza Kayıtları',
                'ordering': ['-bakim_tarihi'],
            },
        ),
        migrations.AddField(
            model_name='envanter',
            name='depolama_alani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envanter_stoklari', to='envanter.depolamaalani', verbose_name='Bulunduğu Depo/Lokasyon (Zimmetli değilse)'),
        ),
        migrations.CreateModel(
            name='SarfMalzemesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Malzeme Adı')),
                ('stok_miktari', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Mevcut Stok Miktarı')),
                ('birim', models.CharField(default='Adet', max_length=20, verbose_name='Birim (Adet, kg, litre)')),
                ('min_stok_seviyesi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum Stok Seviyesi (Uyarı Tetikleyici)')),
                ('depolama_alani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envanter.depolamaalani', verbose_name='Bulunduğu Depo/Lokasyon')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envanter.envanterkategorisi', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Sarf Malzemesi',
                'verbose_name_plural': 'Sarf Malzemeleri',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='SarfMalzemeHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tipi', models.CharField(choices=[('GIRIS', 'Stok Girişi (Satın Alma/Üretim)'), ('CIKIS', 'Stok Çıkışı (Kullanım/Zimmet)')], max_length=10, verbose_name='Hareket Tipi')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hareket Miktarı')),
                ('hareket_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama/Belge Referansı')),
                ('ilgili_proje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.proje', verbose_name='İlgili Proje (Opsiyonel)')),
                ('yapan_personel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan Personel')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_hareketleri', to='envanter.sarfmalzemesi', verbose_name='Sarf Malzemesi')),
            ],
            options={
                'verbose_name': 'Sarf Malzeme Hareketi',
                'verbose_name_plural': 'Sarf Malzeme Hareketleri',
                'ordering': ['-hareket_tarihi'],
            },
        ),
    ]
