# Generated by Django 5.2.7 on 2025-10-30 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_proje_arsa_paydasi_ortak_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsTakvimiGorevi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorev_adi', models.CharField(max_length=255)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('tamamlanma_orani', models.PositiveIntegerField(default=0, help_text='Yüzde (%) olarak')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_gorevler', to='saha.istakvimigorevi')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_takvimi', to='projects.proje')),
            ],
            options={
                'verbose_name': 'İş Takvimi Görevi',
                'verbose_name_plural': 'İş Takvimi Görevleri',
                'ordering': ['baslangic_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SahaRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True)),
                ('metin', models.TextField(verbose_name='Günlük Rapor Özeti')),
                ('fotograf1', models.ImageField(blank=True, null=True, upload_to='uploads/saha_fotograflari/')),
                ('fotograf2', models.ImageField(blank=True, null=True, upload_to='uploads/saha_fotograflari/')),
                ('fotograf3', models.ImageField(blank=True, null=True, upload_to='uploads/saha_fotograflari/')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saha_raporlari', to='projects.proje')),
                ('raporu_yazan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saha_raporlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Günlük Saha Raporu',
                'verbose_name_plural': 'Günlük Saha Raporları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='TahliyeTakibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahliye_edildi_mi', models.BooleanField(default=False, verbose_name='Tahliye Edildi')),
                ('elektrik_kesildi_mi', models.BooleanField(default=False, verbose_name='Elektrik Kesildi')),
                ('su_kesildi_mi', models.BooleanField(default=False, verbose_name='Su Kesildi')),
                ('dogalgaz_kesildi_mi', models.BooleanField(default=False, verbose_name='Doğalgaz Kesildi')),
                ('notlar', models.TextField(blank=True, null=True)),
                ('bagimsiz_bolum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tahliye_durumu', to='projects.bagimsizbolum')),
            ],
            options={
                'verbose_name': 'Tahliye Takip Kaydı',
                'verbose_name_plural': 'Tahliye Takip Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='Taseron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=255)),
                ('yetkili_kisi', models.CharField(blank=True, max_length=150, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('uzmanlik_alani', models.CharField(blank=True, max_length=200, null=True)),
                ('sozlesme_belgesi', models.FileField(blank=True, null=True, upload_to='uploads/taseron_sozlesmeleri/')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taseronlar', to='projects.proje')),
            ],
            options={
                'verbose_name': 'Taşeron',
                'verbose_name_plural': 'Taşeronlar',
                'ordering': ['firma_adi'],
            },
        ),
    ]
