# Generated by Django 5.2.7 on 2025-10-31 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_proje_toplam_butce'),
        ('saha', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tahliyetakibi',
            options={'verbose_name': 'Tahliye Takibi', 'verbose_name_plural': 'Tahliye Takip Kayıtları'},
        ),
        migrations.RemoveField(
            model_name='tahliyetakibi',
            name='dogalgaz_kesildi_mi',
        ),
        migrations.RemoveField(
            model_name='tahliyetakibi',
            name='elektrik_kesildi_mi',
        ),
        migrations.RemoveField(
            model_name='tahliyetakibi',
            name='su_kesildi_mi',
        ),
        migrations.RemoveField(
            model_name='tahliyetakibi',
            name='tahliye_edildi_mi',
        ),
        migrations.AddField(
            model_name='tahliyetakibi',
            name='elektrik_kesildi',
            field=models.BooleanField(default=False, verbose_name='Elektrik Kesildi mi?'),
        ),
        migrations.AddField(
            model_name='tahliyetakibi',
            name='gaz_kesildi',
            field=models.BooleanField(default=False, verbose_name='Doğalgaz Kesildi mi?'),
        ),
        migrations.AddField(
            model_name='tahliyetakibi',
            name='malik_tahliye_etti',
            field=models.BooleanField(default=False, verbose_name='Malik Tahliyeyi Gerçekleştirdi mi?'),
        ),
        migrations.AddField(
            model_name='tahliyetakibi',
            name='proje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.proje', verbose_name='İlgili Proje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tahliyetakibi',
            name='son_kontol_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Kontrol Tarihi'),
        ),
        migrations.AddField(
            model_name='tahliyetakibi',
            name='su_kesildi',
            field=models.BooleanField(default=False, verbose_name='Su Kesildi mi?'),
        ),
        migrations.AddField(
            model_name='tahliyetakibi',
            name='yikima_hazir',
            field=models.BooleanField(default=False, verbose_name='Yıkıma Hazır mı?'),
        ),
        migrations.AlterField(
            model_name='tahliyetakibi',
            name='bagimsiz_bolum',
            field=models.ForeignKey(help_text='Hangi daire, dükkan veya mülkün tahliyesi takip ediliyor.', on_delete=django.db.models.deletion.PROTECT, to='projects.bagimsizbolum', verbose_name='Takip Edilen Bağımsız Bölüm'),
        ),
        migrations.AlterField(
            model_name='tahliyetakibi',
            name='notlar',
            field=models.TextField(blank=True, null=True, verbose_name='Tahliye Notları'),
        ),
        migrations.CreateModel(
            name='GunlukSahaRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapor_tarihi', models.DateField(unique=True, verbose_name='Rapor Tarihi')),
                ('hava_durumu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hava Durumu (Örn: Güneşli, Yağmurlu)')),
                ('calisan_sayisi', models.PositiveIntegerField(default=0, verbose_name='Sahadaki Toplam İşçi Sayısı')),
                ('yapilan_is', models.TextField(verbose_name='Bugün Yapılan İşin Özeti')),
                ('karsilasilan_sorunlar', models.TextField(blank=True, null=True, verbose_name='Karşılaşılan Sorunlar ve Çözümler')),
                ('saha_fotografi', models.FileField(blank=True, null=True, upload_to='saha_raporlari/%Y/%m/%d/', verbose_name='Günlük Saha Fotoğrafı')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proje', verbose_name='İlgili Proje')),
                ('raporu_hazirlayan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Raporu Hazırlayan Personel')),
            ],
            options={
                'verbose_name': 'Günlük Saha Raporu',
                'verbose_name_plural': 'Günlük Saha Raporları',
                'ordering': ['-rapor_tarihi'],
            },
        ),
    ]
