# Generated by Django 5.2.7 on 2025-10-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_proje_toplam_butce'),
        ('saha', '0002_alter_tahliyetakibi_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tahliyetakibi',
            unique_together={('proje', 'bagimsiz_bolum')},
        ),
    ]
