# Generated by Django 5.2.7 on 2025-10-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_hisse_hisse_orani_remove_proje_proje_konumu_and_more'),
        ('saha', '0004_delete_saharaporu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunluksaharaporu',
            name='rapor_tarihi',
            field=models.DateField(verbose_name='Rapor Tarihi'),
        ),
        migrations.AlterUniqueTogether(
            name='gunluksaharaporu',
            unique_together={('proje', 'rapor_tarihi')},
        ),
    ]
