# Generated by Django 5.2.7 on 2025-10-31 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0004_depolamaalani_alter_envanter_options_and_more'),
        ('projects', '0009_remove_hisse_hisse_orani_remove_proje_proje_konumu_and_more'),
        ('saha', '0005_alter_gunluksaharaporu_rapor_tarihi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, unique=True, verbose_name='İş Kalemi/Aktivite Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'İş Kalemi (WBS)',
                'verbose_name_plural': 'İş Kalemleri (WBS Tanımları)',
            },
        ),
        migrations.RemoveField(
            model_name='taseron',
            name='proje',
        ),
        migrations.AlterModelOptions(
            name='tahliyetakibi',
            options={'verbose_name': 'Tahliye Takibi', 'verbose_name_plural': 'Tahliye Takipleri'},
        ),
        migrations.RemoveField(
            model_name='gunluksaharaporu',
            name='calisan_sayisi',
        ),
        migrations.RemoveField(
            model_name='gunluksaharaporu',
            name='karsilasilan_sorunlar',
        ),
        migrations.RemoveField(
            model_name='gunluksaharaporu',
            name='raporu_hazirlayan',
        ),
        migrations.RemoveField(
            model_name='gunluksaharaporu',
            name='saha_fotografi',
        ),
        migrations.RemoveField(
            model_name='gunluksaharaporu',
            name='yapilan_is',
        ),
        migrations.RemoveField(
            model_name='tahliyetakibi',
            name='elektrik_kesildi',
        ),
        migrations.RemoveField(
            model_name='tahliyetakibi',
            name='gaz_kesildi',
        ),
        migrations.RemoveField(
            model_name='tahliyetakibi',
            name='malik_tahliye_etti',
        ),
        migrations.RemoveField(
            model_name='tahliyetakibi',
            name='notlar',
        ),
        migrations.RemoveField(
            model_name='tahliyetakibi',
            name='son_kontol_tarihi',
        ),
        migrations.RemoveField(
            model_name='tahliyetakibi',
            name='su_kesildi',
        ),
        migrations.RemoveField(
            model_name='tahliyetakibi',
            name='yikima_hazir',
        ),
        migrations.AddField(
            model_name='gunluksaharaporu',
            name='genel_notlar',
            field=models.TextField(blank=True, null=True, verbose_name='Genel Gün Sonu Notları'),
        ),
        migrations.AddField(
            model_name='gunluksaharaporu',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gunluksaharaporu',
            name='hazirlayan_personel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hazirladigi_saha_raporlari', to=settings.AUTH_USER_MODEL, verbose_name='Raporu Hazırlayan Personel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gunluksaharaporu',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tahliyetakibi',
            name='durum',
            field=models.CharField(choices=[('TAHLIYE_EDILMEDI', 'Tahliye Edilmedi'), ('PLANLANIYOR', 'Tahliye Planlanıyor'), ('TAHLIYE_EDILDI', 'Tahliye Edildi'), ('YASAL_SUREC', 'Yasal Süreçte')], default='TAHLIYE_EDILMEDI', max_length=50, verbose_name='Tahliye Durumu'),
        ),
        migrations.AddField(
            model_name='tahliyetakibi',
            name='gerceklesen_tahliye_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Gerçekleşen Tahliye Tarihi'),
        ),
        migrations.AddField(
            model_name='tahliyetakibi',
            name='planlanan_tahliye_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Planlanan Tahliye Tarihi'),
        ),
        migrations.AddField(
            model_name='tahliyetakibi',
            name='sorumlu_personel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Personel'),
        ),
        migrations.AlterField(
            model_name='gunluksaharaporu',
            name='hava_durumu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hava Durumu'),
        ),
        migrations.AlterField(
            model_name='gunluksaharaporu',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saha_raporlari', to='projects.proje', verbose_name='İlgili Proje'),
        ),
        migrations.AlterField(
            model_name='gunluksaharaporu',
            name='rapor_tarihi',
            field=models.DateField(unique_for_date='rapor_tarihi', verbose_name='Rapor Tarihi'),
        ),
        migrations.AlterField(
            model_name='tahliyetakibi',
            name='bagimsiz_bolum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.bagimsizbolum', verbose_name='İlgili Bağımsız Bölüm'),
        ),
        migrations.AlterField(
            model_name='tahliyetakibi',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.proje', verbose_name='İlgili Proje'),
        ),
        migrations.CreateModel(
            name='IsGuvenligiKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kayit_tarihi', models.DateTimeField(verbose_name='Olay Tarihi ve Saati')),
                ('kayit_tipi', models.CharField(choices=[('KAZA', 'İş Kazası'), ('OLAY', 'Ramak Kala Olay'), ('TESPIT', 'Güvenlik İhlali Tespiti')], max_length=20, verbose_name='Kayıt Tipi')),
                ('aciklama', models.TextField(verbose_name='Olayın/Tespiti Detaylı Açıklaması')),
                ('yaralanma_durumu', models.BooleanField(default=False, verbose_name='Yaralanma/Hasar Var mı?')),
                ('alınan_onlemler', models.TextField(blank=True, null=True, verbose_name='Olay Sonrası Alınan Önlemler')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proje', verbose_name='İlgili Proje')),
                ('raporlayan_personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_guvenligi_kayitlari', to=settings.AUTH_USER_MODEL, verbose_name='Raporlayan Personel')),
            ],
            options={
                'verbose_name': 'İş Güvenliği Kaydı',
                'verbose_name_plural': 'İş Güvenliği Kayıtları',
                'ordering': ['-kayit_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='KaliteKontrolFormu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denetim_tarihi', models.DateField(verbose_name='Denetim Tarihi')),
                ('denetim_sonucu', models.CharField(choices=[('ONAYLANDI', 'Kalite Standartlarına Uygun'), ('REDDEDILDI', 'Düzeltme Gerekiyor'), ('BEKLEMEDE', 'Denetim Bekleniyor')], default='BEKLEMEDE', max_length=20, verbose_name='Sonuç')),
                ('tespit_edilen_eksikler', models.TextField(blank=True, null=True, verbose_name='Tespit Edilen Eksikler/Uygunsuzluklar')),
                ('dof_gerekiyor_mu', models.BooleanField(default=False, verbose_name='Düzeltici Önleyici Faaliyet (DÖF) Gerekiyor mu?')),
                ('denetleyen_personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yaptigi_kalite_denetimleri', to=settings.AUTH_USER_MODEL, verbose_name='Denetimi Yapan Personel')),
                ('is_kalemi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saha.isturu', verbose_name='Denetlenen İş Kalemi')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proje', verbose_name='İlgili Proje')),
            ],
            options={
                'verbose_name': 'Kalite Kontrol Formu',
                'verbose_name_plural': 'Kalite Kontrol Formları',
                'ordering': ['-denetim_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SahaEkipmanAtamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim_suresi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kullanım Süresi (Saat/Adet)')),
                ('kullanim_birimi', models.CharField(default='Saat', max_length=20, verbose_name='Kullanım Birimi')),
                ('aciklama', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanım Amacı')),
                ('ekipman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envanter.envanter', verbose_name='Kullanılan Ekipman/Araç')),
                ('rapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekipman_atamalari', to='saha.gunluksaharaporu', verbose_name='Günlük Saha Raporu')),
            ],
            options={
                'verbose_name': 'Saha Ekipman Ataması',
                'verbose_name_plural': 'Saha Ekipman Atamaları',
            },
        ),
        migrations.CreateModel(
            name='SahaIlerlemeKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yapilan_is_ozeti', models.TextField(verbose_name='Yapılan İşin Özeti')),
                ('ilerleme_yuzdesi', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Bu İş Kaleminde Kaydedilen Günlük İlerleme (%)')),
                ('is_turu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saha.isturu', verbose_name='Yapılan İş Kalemi')),
                ('rapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilerleme_kayitlari', to='saha.gunluksaharaporu', verbose_name='Günlük Saha Raporu')),
            ],
            options={
                'verbose_name': 'Saha İlerleme Kaydı',
                'verbose_name_plural': 'Saha İlerleme Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='SahaPersonelAtamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calisma_saati', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Çalışma Saati')),
                ('gorev_tanimi', models.CharField(max_length=255, verbose_name='Yaptığı İşin Tanımı')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Çalışan Personel')),
                ('rapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_atamalari', to='saha.gunluksaharaporu', verbose_name='Günlük Saha Raporu')),
            ],
            options={
                'verbose_name': 'Saha Personel Ataması',
                'verbose_name_plural': 'Saha Personel Atamaları',
            },
        ),
        migrations.DeleteModel(
            name='IsTakvimiGorevi',
        ),
        migrations.DeleteModel(
            name='Taseron',
        ),
    ]
